{% set name = "pandavro" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d99102e93b45f9a2d52a284fb4c1055ad6c32ba1569cb21a71c02eceb8a7393b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1
    - pip
  run:
    - python >=3.6.1
    - fastavro >=1.5.1,<1.6.0
    - numpy >=1.15.4
    - pandas >=1.1

test:
  imports:
    - pandavro

about:
  home: https://github.com/ynqa/pandavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The interface between Avro and pandas DataFrame
  doc_url: https://github.com/ynqa/pandavro/blob/master/README.md
  dev_url: https://github.com/ynqa/pandavro

extra:
  recipe-maintainers:
    - rabbit72
