{% set name = "pandavro" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00398a19d5274c7d805c2782ba69dabaa383a8fd5c4f9699100765475df8ec5a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1
    - pip
  run:
    - python >=3.6.1
    - fastavro >=1.5.1,<1.6.0
    - numpy >=1.15.4
    - pandas >=1.1

test:
  imports:
    - pandavro

about:
  home: https://github.com/ynqa/pandavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The interface between Avro and pandas DataFrame
  doc_url: https://github.com/ynqa/pandavro/blob/master/README.md
  dev_url: https://github.com/ynqa/pandavro

extra:
  recipe-maintainers:
    - rabbit72
