schema_version: 1

context:
  name: pandavro
  version: "1.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4f2b7b6823522f54e8bfe33c091fb29898349892b70634f46c928e6a42a76e69

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - fastavro >=1.5.1,<1.6.0
    - numpy >=1.15.4
    - pandas >=1.1

tests:
  - python:
      imports:
        - pandavro
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MIT
  license_file: LICENSE
  summary: The interface between Avro and pandas DataFrame
  homepage: https://github.com/ynqa/pandavro
  repository: https://github.com/ynqa/pandavro
  documentation: https://github.com/ynqa/pandavro/blob/master/README.md

extra:
  recipe-maintainers:
    - rabbit72

